services:
  postgres:
    image: registry.d-sektionen.se/hackathon.webbu.se_postgres:production
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_DB: hackathon
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - internal
    restart: unless-stopped

  nextjs:
    image: registry.d-sektionen.se/hackathon.webbu.se:production
    ports:
      - "127.0.0.1:8416:3000"
    environment:
      NEXT_PUBLIC_BASE_URL: https://hackathon.webbu.se
      NEXT_PUBLIC_API_BASE_URL: https://hackathon.webbu.se/api
      INTERNAL_API_BASE_URL: http://api:3000
    networks:
      - internal
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: registry.d-sektionen.se/hackathon.webbu.se_api:production
    ports:
      - "127.0.0.1:8417:3000"
    environment:
      CORS_ALLOWED_ORIGIN: https://hackathon.webbu.se
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:

volumes:
  postgres_data:
