services:
  postgres:
    image: ""
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ".dev/db/dumps:/dumps"
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: no

  nextjs:
    image: ""
    build:
      context: nextjs
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs/app:/app/app
      - ./nextjs/components:/app/components
      - ./nextjs/public:/app/public
      - ./nextjs/lib:/app/lib
    env_file: .env
    environment:
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
      INTERNAL_API_BASE_URL: http://localhost:3001
    restart: no

  api:
    image: ""
    build:
      context: api
      dockerfile: Dockerfile.development
    volumes:
      - ./api/app:/app/app
    ports:
      - "3001:3000"
    environment:
      CORS_ALLOWED_ORIGIN: http://localhost:3000
    env_file: .env
    restart: no
